# Generated by Django 4.2.9 on 2026-02-27 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_formulario', to='clientes.cliente')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_formulario', to='contratos.modelocontrato')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_formulario', to='core.organizacao')),
            ],
            options={
                'verbose_name': 'Link de Formulário',
                'verbose_name_plural': 'Links de Formulário',
                'ordering': ['-criado_em'],
            },
        ),
    ]
