# Generated by Django 4.2.9 on 2026-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkformulario',
            name='email_destinatario',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
