# Generated by Django 4.2.9 on 2026-05-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
